version: "3"
services:
  web:
    image: resistcs/website:v1
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet:
